version: '3.8'

services:
  postgres:
    container_name: postgres_db
    image: postgres:latest
    restart: always
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - ./postgres_db:/var/lib/postgresql/data

  fimi_redis:
    container_name: fimi_redis
    image: redis:alpine
    expose:
      - 6379
    ports:
      - 6379:6379
    restart: unless-stopped

  redis_commander:
    container_name: redis_commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:fimi_redis:6379
    ports:
      - 8088:8081
    depends_on:
      - fimi_redis
    restart: unless-stopped

networks:
  default:
    driver: bridge
  mynetwork:
    driver: bridge


volumes:
    postgres_db:
        driver: local
# volumes:
#   mongo1data:
#   mongo1config:
#   mongo2data:
#   mongo2config:
#   mongo3data:
#   mongo3config:
#   sharedconfig:
